title: Maximilian Tomio
description: To greatness, one step at a time
site_title: 'Maximilian Tomio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: agoodnap
blog_url: https://www.itch.io/agoodnap
email: tomio.maximilian@gmail.com
twitter_username: agoodnap
itch_username: agoodnap
linkedin_id: maximilian-tomio-80aa38152

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 